image: node:12-alpine
stages:
  - test
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

.node_base: &node_base
  stage: test
  before_script:
    - apk add make nasm autoconf automake libtool dpkg pkgconfig libpng libpng-dev g++
    - yarn install --frozen-lockfile

build:
  <<: *node_base
  stage: test
  script:
    - yarn run build

lint:
  <<: *node_base
  script:
    - yarn run lint

