image: node:8-alpine

cache:
  paths:
  - node_modules/

before_script:
  - npm i -g yarn
  - yarn
  - cp .env.example .env

build:
  script:
    - yarn run lint
    - yarn run build
    - yarn run export
