image: node:10-alpine
stages:
  - build
  - test
  - deploy
  - analyze
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

build:
  stage: build
  before_script:
    - npm i -g yarn
    - yarn
    - rm -rf .cache
  script:
    - yarn run build --prefix-paths bytecode-website
    - mv public build
  artifacts:
    paths:
      - build/

lint:
  stage: test
  before_script:
    - npm i -g yarn
    - yarn
  script:
    - yarn run lint

test_jest:
  stage: test
  before_script:
    - npm i -g yarn
    - yarn
  script:
    - yarn run test:ci

pages:
  image: alpine:3.9
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public

include:
  - template: Code-Quality.gitlab-ci.yml
code_quality:
  stage: analyze
  dependencies: []

