cache:
  paths:
  - node_modules/

before_script:
  - apk add python make g++
  - npm i -g yarn
  - yarn
  - cp .env.example .env

build:
  image: node:10-alpine
  script:
    - yarn run lint
    - yarn run build
