files:
  include:
    - 'src/**/*.scss'

rules:
    indentation:
        - 4
        -
            size: 4
    property-sort-order:
        - 1
        -
            order: smacss
    class-name-format:
        - allow-leading-underscore: false
        - convention: hyphenatedbem
