# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytecode-website
  namespace: bytecode-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytecode-website
      tier: bytecode-website
  template:
    metadata:
      labels:
        app: bytecode-website
        tier: bytecode-website
    spec:
      imagePullSecrets:
        - name: registrycredentials
      containers:
        - name: bytecode-website
          image: registry.bytecode.nl/bytecode/bytecode-website:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          ports:
          - containerPort: 80

# SVC
---
apiVersion: v1
kind: Service
metadata:
  name: bytecode-website
  namespace: bytecode-website
spec:
  selector:
    app: bytecode-website
    tier: bytecode-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bytecode-website
  namespace: bytecode-website
spec:
  rules:
  - host: bytecode.nl
    http:
      paths:
      - path: /
        backend:
          serviceName: bytecode-website
          servicePort: 80
